name: nobody
description: works for you
version: 1.0.0
publish_to: none
environment:
  sdk: '>=3.2.0 <4.0.0'
dependencies:
  meta: ^1.8.0
  lints: ^3.0.0
  freezed_annotation: ^2.2.0
  uuid: ^4.1.0
  collection: ^1.16.0
  flutter_rust_bridge: 2.0.0-dev.3

dev_dependencies:
  build_runner: ^2.4.7
  freezed: ^2.1.0+1
  ffigen: ^8.0.0
