# Read about `build.yaml` at https://pub.dev/packages/build_config
builders:
  # name of the builder
  future_builder:
    # library URI containing the builder - maps to `lib/future_builder_library_generator.dart`
    import: "package:codegen/builder.dart"
    # Name of the function in the above library to call.
    builder_factories: ["futureBuilder"]
    # The mapping from the source extension to the generated file extension
    build_extensions: {".dart": [".future.dart"]}
    # Will automatically run on any package that depends on it
    auto_apply: dependents
    # Generate the output directly into the package, not to a hidden cache dir
    build_to: source
    # The input files to match against
    defaults:
      generate_for:
        include:
          - lib/**.dart

