name: nobody
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.2.0-42.2.beta

dependencies:
  puppeteer: any
  codegen: 
    path: ../codegen
  termo:
    path: ../termo
  collection: ^1.18.0


dev_dependencies:
  build_runner: any
  source_gen: any
