name: nobody
description: works for you
version: 2.0.4
homepage: "https://xo.rs"

environment:
  sdk: ^3.3.0

dependencies:
  puppeteer: ^3.4.0
  collection: ^1.18.0
  flat_buffers: ^2.0.5
  encrypt: ^5.0.3
  dio: ^5.3.3
  excel: ^2.1.0
  archive: ^3.4.10
  coco: ^1.0.2
  oauth2_manager: ^1.0.0
  nogen: ^2.0.0

dev_dependencies:
  build_runner: any
  source_gen: any





