[package]
name = "nomo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termo = { version = "0.16.0", path = "../../termo" }
