name: Release Workflow

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check commit message
        id: check-message
        run: |
          commit_message=$(git log -1 --pretty=%B)
          echo "Commit message: $commit_message"
          if [[ "$commit_message" == *"release"* ]]; then
            echo "::set-output name=trigger_release::true"
          fi

      - name: Tag the commit
        if: steps.check-message.outputs.trigger_release == 'true'
        run: |
          TAG_NAME="v$(date +'%Y.%m.%d.%H.%M.%S')"
          git tag $TAG_NAME
          git push origin $TAG_NAME

      - name: Build project
        if: steps.check-message.outputs.trigger_release == 'true'
        run: |
          cargo build --release
          strip target/release/YOUR_PROJECT_NAME # Adjust if necessary

      - name: Create Release
        if: steps.check-message.outputs.trigger_release == 'true'
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/release/YOUR_PROJECT_NAME
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
