name: Rust Project Release

on:
  push:
    branches:
      - main

jobs:
  release:
    # If commit message contains 'release', then run the job
    if: contains(github.event.head_commit.message, 'release')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Determine Release Tag
        id: release_tag
        run: echo "RELEASE_TAG=v$(date +'%Y.%m.%d.%H%M%S')" >> $GITHUB_ENV

      - name: Create Release Tag and Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          release_name: Rust Project Release ${{ env.RELEASE_TAG }}
          draft: false
          prerelease: false

      - name: Build Rust Project
        run: |
          cargo build --release

      - name: Upload Artifacts to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./target/release/your_artifact_name
          asset_name: your_artifact_name-${{ env.RELEASE_TAG }}
          asset_content_type: application/octet-stream
